# Generated by Django 5.0 on 2023-12-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_genre_snippet_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='genre',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='snippet.genre'),
        ),
    ]
