# Generated by Django 5.0 on 2023-12-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0007_genre_snippet_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
