# Generated by Django 5.0 on 2023-12-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0008_remove_snippet_genre_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='department',
            field=models.CharField(choices=[('1', 'СИТ'), ('2', 'СК')], default='1', max_length=1),
        ),
    ]
