# Generated by Django 5.0 on 2023-12-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('last_name', models.CharField(default='', max_length=155)),
                ('first_name', models.CharField(default='', max_length=155)),
                ('middle_name', models.CharField(default='', max_length=155)),
                ('iin_or_bin', models.CharField(default='', max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('mail_address', models.EmailField(default='', max_length=254)),
                ('questions', models.CharField(default='', max_length=155)),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
