# Generated by Django 5.0 on 2023-12-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0002_sendmessage_delete_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='name',
        ),
    ]
