# Generated by Django 5.0 on 2023-12-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0003_remove_sendmessage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='phone_number',
            field=models.CharField(default='8', max_length=155),
        ),
    ]
